import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

export default function Home() {
  return (
    <>
      <Head>
        <title>My DnD Adventure Logger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Oldbook.css</h1>
        <h2>Introduction</h2>
        This is oldbook.css. It's a single drag and drop css file that applies a
        clean, old-school parchment style to your sites. Here's <b>bold</b>{" "}
        text, here's <i>italic</i> text.
        <ul>
          <li>Unordered list item</li>
        </ul>
        <ol>
          <li>Ordered list item</li>
        </ol>
        <p className="has-dropcap">
          Use the class "has-dropcap" to add dropcaps to the start of
          paragraphs. Testing testing testing, how does this even work as a drop
          cap thing anyways. Testing testing testing, how does this even work as
          a drop cap thing anyways. Testing testing testing, how does this even
          work as a drop cap thing anyways. Testing testing testing, how does
          this even work as a drop cap thing anyways.
        </p>
        <blockquote>Blockquote</blockquote>
        <table>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
          </tr>
          <tr>
            <td>A</td>
            <td>B</td>
          </tr>
          <tr>
            <td>C</td>
            <td>D</td>
          </tr>
        </table>
        <br />
      </main>
    </>
  );
}
